# Generated by Django 4.2.25 on 2025-11-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='news/'),
        ),
    ]
